# Site settings
title: Alejandro López Sánchez
description: Personal portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alejandro López
user_title: Frontend engineer
email: a.lopez.sanchez@outlook.es
twitter_username: aristalex
github_username:  alopezsanchez

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
